"""Opt-in integration checks against a sourced ROS 2 installation.

Run: RLSOK_RUN_ROS_GRAPH_TESTS=1 python3 -B test_ros_graph.py -v
The test chooses a private high-number domain, restricts discovery to localhost,
and refuses a domain containing other nodes. It only creates action servers;
every received goal is rejected and counted, and zero requests are asserted.

By default all three endpoints use FollowJointTrajectory. To exercise installed
custom interfaces, set RLSOK_TEST_CARTESIAN_ACTION and RLSOK_TEST_TP_ACTION to
package/action/Type. No custom interface package is generated by this test.
An unsourced ROS installation or absent explicit opt-in produces a clear skip.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import secrets
import subprocess
import sys
import tempfile
import threading
import time
import unittest
from uuid import uuid4


HERE = Path(__file__).resolve().parent
STANDARD_ACTION = "control_msgs/action/FollowJointTrajectory"


@unittest.skipUnless(os.environ.get("RLSOK_RUN_ROS_GRAPH_TESTS") == "1",
                     "set RLSOK_RUN_ROS_GRAPH_TESTS=1 to run isolated real ROS tests")
class RealRosGraphTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        try:
            import rclpy
            from rclpy.action import ActionServer, CancelResponse, GoalResponse
            from rclpy.context import Context
            from rclpy.executors import SingleThreadedExecutor
            from rclpy.utilities import get_rmw_implementation_identifier
            from rosidl_runtime_py.utilities import get_action
        except ImportError as error:
            raise unittest.SkipTest(f"source ROS 2 and its action interfaces first: {error}") from error
        cls.actual_distro = os.environ.get("ROS_DISTRO")
        if not cls.actual_distro:
            raise unittest.SkipTest("ROS_DISTRO is missing; source a ROS 2 installation")
        cls.prior_environment = {
            key: os.environ.get(key)
            for key in ("ROS_DOMAIN_ID", "ROS_LOCALHOST_ONLY", "ROS_AUTOMATIC_DISCOVERY_RANGE")
        }
        cls.addClassCleanup(cls.restore_environment)
        cls.domain_id = 200 + secrets.randbelow(33)
        os.environ.update({"ROS_DOMAIN_ID": str(cls.domain_id), "ROS_LOCALHOST_ONLY": "1",
                           "ROS_AUTOMATIC_DISCOVERY_RANGE": "LOCALHOST"})
        cls.context = Context()
        rclpy.init(args=[], context=cls.context)
        cls.actual_rmw = get_rmw_implementation_identifier()
        cls.node, cls.executor, cls.thread, cls.servers = None, None, None, []
        cls.addClassCleanup(cls.cleanup_ros)
        cls.node = rclpy.create_node(
            f"rlsok_isolated_test_{uuid4().hex}", context=cls.context,
            use_global_arguments=False, enable_rosout=False, start_parameter_services=False,
        )
        cls.executor = SingleThreadedExecutor(context=cls.context)
        cls.executor.add_node(cls.node)
        # Observe before adding server endpoints. Abort rather than joining a busy domain.
        deadline = time.monotonic() + 2.0
        while time.monotonic() < deadline:
            cls.executor.spin_once(timeout_sec=0.1)
        own_identity = (cls.node.get_name(), cls.node.get_namespace())
        if any(identity != own_identity for identity in cls.node.get_node_names_and_namespaces()):
            raise RuntimeError("isolated test domain already contains other nodes; refusing to continue")
        cls.requests = {"goals": 0, "cancels": 0, "executions": 0}

        def goal(_request):
            cls.requests["goals"] += 1
            return GoalResponse.REJECT

        def cancel(_handle):
            cls.requests["cancels"] += 1
            return CancelResponse.REJECT

        def execute(_handle):
            cls.requests["executions"] += 1
            raise AssertionError("read-only collector must never execute an action")

        namespace = f"/rlsok_test_{uuid4().hex}"
        cls.paths = [
            ("joint", namespace + "/trajectory", STANDARD_ACTION),
            ("cartesian", namespace + "/cartesian", os.environ.get("RLSOK_TEST_CARTESIAN_ACTION", STANDARD_ACTION)),
            ("tp", namespace + "/program", os.environ.get("RLSOK_TEST_TP_ACTION", STANDARD_ACTION)),
        ]
        for _path_id, endpoint, action_type in cls.paths:
            server = ActionServer(cls.node, get_action(action_type), endpoint, execute_callback=execute,
                                  goal_callback=goal, cancel_callback=cancel)
            cls.servers.append(server)
        cls.thread = threading.Thread(target=cls.executor.spin, daemon=True)
        cls.thread.start()
        print(f"\nActual ROS_DISTRO={cls.actual_distro}; isolated ROS_DOMAIN_ID={cls.domain_id}; "
              f"action types={[path[2] for path in cls.paths]}", flush=True)

    @classmethod
    def restore_environment(cls):
        for key, value in cls.prior_environment.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value

    @classmethod
    def cleanup_ros(cls):
        try:
            if cls.executor is not None:
                cls.executor.shutdown(timeout_sec=5.0)
            if cls.thread is not None:
                cls.thread.join(timeout=5.0)
        finally:
            try:
                for server in reversed(cls.servers):
                    server.destroy()
                if cls.node is not None:
                    cls.node.destroy_node()
            finally:
                cls.context.shutdown()

    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix="rlsok-real-graph-")
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        (self.root / "calibration.txt").write_bytes(b"local calibration fixture\n")
        (self.root / "tool.json").write_text(json.dumps({
            "observedAt": "2026-09-01T00:00:00.000Z", "tool": "observed-tool"
        }), encoding="utf-8")
        self.config = {
            "schemaVersion": 1, "id": "isolated-real-graph", "mode": "shadow",
            "environment": {"rosDistro": self.actual_distro, "rmwImplementation": self.actual_rmw,
                            "domainId": self.domain_id},
            "robot": {"deviceId": "isolated-cell", "model": "test-servers", "controller": "test-only",
                      "urdfSha256": "0" * 64},
            "jointOrder": ["joint_1"], "maxObservationAgeMs": 5000,
            "facts": [
                {"id": "calibration", "kind": "file_sha256", "path": "calibration.txt", "expected": "0" * 64},
                {"id": "tool", "kind": "json_value", "path": "tool.json", "pointer": "/tool", "expected": "not-the-observed-value"},
            ],
            "paths": [self.profile_path(path_id, endpoint, action_type)
                      for path_id, endpoint, action_type in self.paths],
        }

    def profile_path(self, path_id, endpoint, action_type):
        if action_type == STANDARD_ACTION:
            adapter, fields = "joint_trajectory", {"jointNames": "/trajectory/joint_names", "points": "/trajectory/points"}
        elif path_id == "tp":
            adapter, fields = "tp_program", {"program": "/program_name", "allowedPrograms": ["TEST_ONLY"]}
        elif action_type.endswith("/JogCartesian"):
            # Public fanucpy JogCartesian is a relative mm/degrees contract.
            adapter, fields = "cartesian_delta", {
                "translation": ["/delta_x_mm", "/delta_y_mm", "/delta_z_mm"],
                "rotation": ["/delta_w_deg", "/delta_p_deg", "/delta_r_deg"],
                "velocity": "/velocity_mm_s", "frame": "/header/frame_id", "expectedFrame": "test_frame",
                "maxTranslationMm": 1, "maxRotationDeg": 1, "maxVelocityMmS": 1,
            }
        else:
            adapter, fields = "cartesian_pose", {"position": "/pose/position", "orientation": "/pose/orientation",
                                                 "frame": "/frame", "expectedFrame": "test_frame"}
        return {"id": path_id, "endpoint": endpoint, "actionType": action_type, "adapter": adapter,
                "fields": fields, "interfaceSha256": "0" * 64, "checks": ["calibration", "tool"]}

    def run_collector(self):
        config_file, output = self.root / "profile.json", self.root / "observation.json"
        config_file.write_text(json.dumps(self.config), encoding="utf-8")
        result = subprocess.run(
            [sys.executable, "-B", str(HERE / "collect.py"), "--profile", str(config_file),
             "--output", str(output), "--discovery-seconds", "3"],
            text=True, capture_output=True, timeout=30, env=dict(os.environ), check=False,
        )
        return result, output

    def tearDown(self):
        self.assertEqual(self.requests, {"goals": 0, "cancels": 0, "executions": 0})

    def test_three_endpoints_are_collected_without_goal_requests(self):
        result, output = self.run_collector()
        self.assertEqual(result.returncode, 0, result.stderr)
        observation = json.loads(output.read_text(encoding="utf-8"))
        self.assertEqual(observation["environment"]["rosDistro"], self.actual_distro)
        self.assertEqual(observation["environment"]["domainId"], self.domain_id)
        self.assertEqual(len(observation["paths"]), 3)
        for actual, (_path_id, endpoint, action_type) in zip(observation["paths"], self.paths):
            self.assertEqual((actual["endpoint"], actual["actionType"], actual["serverCount"]),
                             (endpoint, action_type, 1))
            self.assertRegex(actual["interfaceSha256"], r"^[a-f0-9]{64}$")
            self.assertNotEqual(actual["interfaceSha256"], "0" * 64)
        self.assertEqual(observation["facts"][1]["value"], "observed-tool")
        self.assertEqual(observation["facts"][1]["observedAt"], "2026-09-01T00:00:00.000Z")

    def test_missing_server_fails_without_observation_or_requests(self):
        self.config["paths"][0]["endpoint"] += "_missing"
        result, output = self.run_collector()
        self.assertEqual(result.returncode, 2, result.stderr)
        self.assertIn("action server not observed", result.stderr)
        self.assertFalse(output.exists())

    def test_installed_standard_interface_fingerprint_is_reproducible(self):
        result = subprocess.run(
            [sys.executable, "-B", str(HERE / "collect.py"), "--describe-interface", STANDARD_ACTION],
            text=True, capture_output=True, timeout=15, check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        description = json.loads(result.stdout)
        canonical = json.dumps(description["typeTree"], sort_keys=True, separators=(",", ":"),
                               ensure_ascii=True).encode("utf-8")
        self.assertEqual(description["interfaceSha256"], hashlib.sha256(canonical).hexdigest())
        self.assertIn("trajectory_msgs/msg/JointTrajectory", description["typeTree"]["definitions"])


if __name__ == "__main__":
    unittest.main()
